-- ============================================================
-- L7VP 达梦 DM8 数据库建表脚本 (v2.0)
-- Schema: DIG_GEO (替代旧 L7VP_PROJECTS)
-- 表数量: 9 张
-- 执行前确保已连接到达梦数据库
-- ============================================================

-- 创建 Schema
CREATE SCHEMA IF NOT EXISTS DIG_GEO;

-- ============================================================
-- 1. PROJECTS — 项目主表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.PROJECTS (
  PROJECT_ID        VARCHAR(50)  PRIMARY KEY,
  PROJECT_NAME      VARCHAR(200),
  DESCRIPTION       VARCHAR(500),
  CREATE_TIME       VARCHAR(50),
  UPDATE_TIME       VARCHAR(50),
  THUMBNAIL         VARCHAR(500),
  ASSET_PACKAGE_IDS VARCHAR(500),
  MAP_CONFIG        VARCHAR(4000)
);

CREATE INDEX IF NOT EXISTS IDX_PROJECTS_NAME       ON DIG_GEO.PROJECTS(PROJECT_NAME);
CREATE INDEX IF NOT EXISTS IDX_PROJECTS_CREATE_TIME ON DIG_GEO.PROJECTS(CREATE_TIME);

COMMENT ON TABLE DIG_GEO.PROJECTS IS '项目主表';
COMMENT ON COLUMN DIG_GEO.PROJECTS.PROJECT_ID IS '项目ID (UUID)';
COMMENT ON COLUMN DIG_GEO.PROJECTS.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN DIG_GEO.PROJECTS.DESCRIPTION IS '项目描述';
COMMENT ON COLUMN DIG_GEO.PROJECTS.CREATE_TIME IS '创建时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN DIG_GEO.PROJECTS.UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN DIG_GEO.PROJECTS.THUMBNAIL IS '缩略图 URL';
COMMENT ON COLUMN DIG_GEO.PROJECTS.ASSET_PACKAGE_IDS IS '资产包ID列表 (JSON数组)';

-- ============================================================
-- 2. DATASETS — 数据集元数据表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASETS (
  DATASET_ID   VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID   VARCHAR(50)  NOT NULL,
  DATASET_NAME VARCHAR(200),
  TYPE         VARCHAR(50),
  METADATA     CLOB,
  FILTER       CLOB,
  CREATE_TIME  VARCHAR(50),

  CONSTRAINT FK_DATASETS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_DATASETS_PROJECT ON DIG_GEO.DATASETS(PROJECT_ID);

COMMENT ON TABLE DIG_GEO.DATASETS IS '数据集元数据表';
COMMENT ON COLUMN DIG_GEO.DATASETS.DATASET_ID IS '数据集ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASETS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.DATASETS.DATASET_NAME IS '数据集名称';
COMMENT ON COLUMN DIG_GEO.DATASETS.TYPE IS '数据源类型: local / remote / raster-tile / vector-tile / doris';
COMMENT ON COLUMN DIG_GEO.DATASETS.METADATA IS 'JSON, 数据集元信息 (columnsMeta, rowCount 等)';
COMMENT ON COLUMN DIG_GEO.DATASETS.FILTER IS 'JSON, 数据集筛选器配置 (relation, children 等)';
COMMENT ON COLUMN DIG_GEO.DATASETS.CREATE_TIME IS '创建时间';

-- ============================================================
-- 3. DATASET_COLUMNS — 数据集列定义表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASET_COLUMNS (
  COLUMN_ID      VARCHAR(50)  PRIMARY KEY,
  DATASET_ID     VARCHAR(50)  NOT NULL,
  COLUMN_NAME    VARCHAR(200),
  COLUMN_TYPE    VARCHAR(50),
  COLUMN_INDEX   INT,
  COLUMN_COMMENT VARCHAR(500),

  CONSTRAINT FK_COLUMNS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_COLUMNS_DATASET ON DIG_GEO.DATASET_COLUMNS(DATASET_ID);

COMMENT ON TABLE DIG_GEO.DATASET_COLUMNS IS '数据集列定义表';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_ID IS '列ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.DATASET_ID IS '所属数据集ID';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_NAME IS '列名 (如"城市", "人口")';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_TYPE IS '数据类型: string / number / boolean / date';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_INDEX IS '列序号 (0开始), 对应 row_data JSON数组下标';
COMMENT ON COLUMN DIG_GEO.DATASET_COLUMNS.COLUMN_COMMENT IS '字段注释 (数据库 REMARKS)';

-- ============================================================
-- 4. DATASET_ROWS — 数据行表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.DATASET_ROWS (
  ROW_ID     VARCHAR(50)  PRIMARY KEY,
  DATASET_ID VARCHAR(50)  NOT NULL,
  ROW_INDEX  INT,
  ROW_DATA   CLOB,

  CONSTRAINT FK_ROWS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_ROWS_DATASET ON DIG_GEO.DATASET_ROWS(DATASET_ID, ROW_INDEX);

COMMENT ON TABLE DIG_GEO.DATASET_ROWS IS '数据行表';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_ID IS '行ID (UUID)';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.DATASET_ID IS '所属数据集ID';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_INDEX IS '行序号 (0开始)';
COMMENT ON COLUMN DIG_GEO.DATASET_ROWS.ROW_DATA IS 'JSON数组, 按 column_index 顺序存储值';

-- ============================================================
-- 5. LAYERS — 图层表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.LAYERS (
  LAYER_ID    VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID  VARCHAR(50)  NOT NULL,
  DATASET_ID  VARCHAR(50),
  LAYER_NAME  VARCHAR(200),
  TYPE        VARCHAR(50),
  VIS_CONFIG  CLOB,
  LAYER_ORDER INT,
  CREATE_TIME VARCHAR(50),

  CONSTRAINT FK_LAYERS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_LAYERS_DATASET
    FOREIGN KEY (DATASET_ID) REFERENCES DIG_GEO.DATASETS(DATASET_ID)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_LAYERS_PROJECT ON DIG_GEO.LAYERS(PROJECT_ID, LAYER_ORDER);

COMMENT ON TABLE DIG_GEO.LAYERS IS '图层配置表';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_ID IS '图层ID (UUID)';
COMMENT ON COLUMN DIG_GEO.LAYERS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.LAYERS.DATASET_ID IS '关联数据集ID (可选)';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_NAME IS '图层名称';
COMMENT ON COLUMN DIG_GEO.LAYERS.TYPE IS '图层类型: BubbleLayer / TileLayer / IconLayer / FlowLayer 等';
COMMENT ON COLUMN DIG_GEO.LAYERS.VIS_CONFIG IS 'JSON, 可视化配置 (颜色、半径、透明度、图标等)';
COMMENT ON COLUMN DIG_GEO.LAYERS.LAYER_ORDER IS '图层叠放顺序';
COMMENT ON COLUMN DIG_GEO.LAYERS.CREATE_TIME IS '创建时间';

-- ============================================================
-- 6. WIDGETS — 组件表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.WIDGETS (
  WIDGET_ID    VARCHAR(50)  PRIMARY KEY,
  PROJECT_ID   VARCHAR(50)  NOT NULL,
  CONTAINER_ID VARCHAR(50),
  WIDGET_NAME  VARCHAR(200),
  TYPE         VARCHAR(50),
  PROPERTIES   CLOB,
  SLOT         VARCHAR(50),
  WIDGET_ORDER INT,

  CONSTRAINT FK_WIDGETS_PROJECT
    FOREIGN KEY (PROJECT_ID) REFERENCES DIG_GEO.PROJECTS(PROJECT_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_WIDGETS_CONTAINER
    FOREIGN KEY (CONTAINER_ID) REFERENCES DIG_GEO.WIDGETS(WIDGET_ID)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_WIDGETS_PROJECT ON DIG_GEO.WIDGETS(PROJECT_ID, WIDGET_ORDER);

COMMENT ON TABLE DIG_GEO.WIDGETS IS '组件配置表';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_ID IS '组件ID (UUID)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.PROJECT_ID IS '所属项目ID';
COMMENT ON COLUMN DIG_GEO.WIDGETS.CONTAINER_ID IS '父容器组件ID (可选, 自引用)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_NAME IS '组件名称';
COMMENT ON COLUMN DIG_GEO.WIDGETS.TYPE IS '组件类型: AnalysisLayout / ZoomControl / Legend 等';
COMMENT ON COLUMN DIG_GEO.WIDGETS.PROPERTIES IS 'JSON, 组件属性配置';
COMMENT ON COLUMN DIG_GEO.WIDGETS.SLOT IS '插槽名 (如 controls)';
COMMENT ON COLUMN DIG_GEO.WIDGETS.WIDGET_ORDER IS '排序序号';

-- ============================================================
-- 7. TILE_CONFIG — 瓦片全局配置表 (单例)
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.TILE_CONFIG (
  ID          VARCHAR(10)  PRIMARY KEY,
  TILE_URL    VARCHAR(500),
  TILE_NAME   VARCHAR(100),
  MIN_ZOOM    INT,
  MAX_ZOOM    INT,
  UPDATE_TIME VARCHAR(50),
  IS_DEFAULT  VARCHAR(10),
  DEFAULT_NUM INT,
  CRS         VARCHAR(50),
  TILE_SCHEME VARCHAR(50),
  ORIGIN      VARCHAR(100)
);

COMMENT ON TABLE DIG_GEO.TILE_CONFIG IS '瓦片全局配置表 (仅1条记录)';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.ID IS '主键, 固定值 "default", 单例';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_URL IS 'XYZ瓦片地址模板 (含 {x} {y} {z} 占位符)';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_NAME IS '底图显示名称 (如 "内网卫星影像")';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.MIN_ZOOM IS '最小缩放级别, 默认0';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.MAX_ZOOM IS '最大缩放级别, 默认18';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.IS_DEFAULT IS '是否默认瓦片: 1=是';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.DEFAULT_NUM IS '默认瓦片排序编号';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.CRS IS '坐标系类型: EPSG:3857 或 EPSG:4326';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.TILE_SCHEME IS '瓦片编号方式: XYZ 或 TMS';
COMMENT ON COLUMN DIG_GEO.TILE_CONFIG.ORIGIN IS '瓦片原点: lng,lat 格式';

-- 插入默认瓦片配置 (高德公开瓦片, 兜底)
-- 使用 MERGE INTO 实现 UPSERT (达梦 DM8 兼容语法)
MERGE INTO DIG_GEO.TILE_CONFIG t
USING (SELECT 'default' AS id FROM DUAL) s
ON (t.ID = s.id)
WHEN MATCHED THEN
  UPDATE SET TILE_URL    = 'https://webrd0{1-4}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
             TILE_NAME   = '高德标准地图',
             MIN_ZOOM    = 0,
             MAX_ZOOM    = 18,
             UPDATE_TIME = TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
WHEN NOT MATCHED THEN
  INSERT (ID, TILE_URL, TILE_NAME, MIN_ZOOM, MAX_ZOOM, UPDATE_TIME)
  VALUES ('default',
          'https://webrd0{1-4}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}',
          '高德标准地图',
          0,
          18,
          TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));

-- ============================================================
-- 8. ICON_CATEGORIES — 图标分类表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.ICON_CATEGORIES (
  CATEGORY_ID   VARCHAR(50)  PRIMARY KEY,
  CATEGORY_NAME VARCHAR(100),
  SORT_ORDER    INT,
  CREATE_TIME   VARCHAR(50)
);

COMMENT ON TABLE DIG_GEO.ICON_CATEGORIES IS '图标分类表';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CATEGORY_ID IS '分类ID (UUID)';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CATEGORY_NAME IS '分类名称 (如 "通信", "军事", "交通")';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.SORT_ORDER IS '排序序号';
COMMENT ON COLUMN DIG_GEO.ICON_CATEGORIES.CREATE_TIME IS '创建时间';

-- ============================================================
-- 9. ICONS — 图标元数据表
-- ============================================================
CREATE TABLE IF NOT EXISTS DIG_GEO.ICONS (
  ICON_ID       VARCHAR(50)  PRIMARY KEY,
  CATEGORY_ID   VARCHAR(50)  NOT NULL,
  LIBRARY_CODE  VARCHAR(100),
  CODE_NAME     VARCHAR(100),
  FILE_NAME     VARCHAR(500),
  ORIGINAL_NAME VARCHAR(500),
  FILE_TYPE     VARCHAR(20),
  FILE_SIZE     BIGINT,
  URL           VARCHAR(500),
  SORT_ORDER    INT,
  CREATE_TIME   VARCHAR(50),

  CONSTRAINT FK_ICONS_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES DIG_GEO.ICON_CATEGORIES(CATEGORY_ID)
    ON DELETE CASCADE,

  CONSTRAINT UNQ_ICON_CODE UNIQUE (CATEGORY_ID, LIBRARY_CODE, CODE_NAME)
);

CREATE INDEX IF NOT EXISTS IDX_ICONS_CATEGORY ON DIG_GEO.ICONS(CATEGORY_ID, SORT_ORDER);
CREATE INDEX IF NOT EXISTS IDX_ICONS_LOOKUP   ON DIG_GEO.ICONS(LIBRARY_CODE, CODE_NAME);

COMMENT ON TABLE DIG_GEO.ICONS IS '图标元数据表';
COMMENT ON COLUMN DIG_GEO.ICONS.ICON_ID IS '图标ID (UUID)';
COMMENT ON COLUMN DIG_GEO.ICONS.CATEGORY_ID IS '所属分类ID';
COMMENT ON COLUMN DIG_GEO.ICONS.LIBRARY_CODE IS '库号 (用户自定义)';
COMMENT ON COLUMN DIG_GEO.ICONS.CODE_NAME IS '代号 (用户自定义)';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_NAME IS '服务器存储文件名 (UUID重命名)';
COMMENT ON COLUMN DIG_GEO.ICONS.ORIGINAL_NAME IS '原始文件名';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_TYPE IS '文件类型: svg / png / jpg 等';
COMMENT ON COLUMN DIG_GEO.ICONS.FILE_SIZE IS '文件大小 (字节)';
COMMENT ON COLUMN DIG_GEO.ICONS.URL IS '图标访问 URL (如 /icons/{categoryId}/{uuid}.{ext})';
COMMENT ON COLUMN DIG_GEO.ICONS.SORT_ORDER IS '分类内排序序号';
COMMENT ON COLUMN DIG_GEO.ICONS.CREATE_TIME IS '创建时间';
