CREATE TABLE "DIG_GEO"."DATASETS"
(
 "DATASET_ID" VARCHAR(50) NOT NULL,
 "PROJECT_ID" VARCHAR(50) NOT NULL,
 "DATASET_NAME" VARCHAR(200) NULL,
 "TYPE" VARCHAR(50) NULL,
 "METADATA" CLOB NULL,
 "CREATE_TIME" VARCHAR(50) NULL,
 "FILTER" CLOB NULL
);
CREATE TABLE "DIG_GEO"."DATASET_COLUMNS"
(
 "COLUMN_ID" VARCHAR(50) NOT NULL,
 "DATASET_ID" VARCHAR(50) NOT NULL,
 "COLUMN_NAME" VARCHAR(200) NULL,
 "COLUMN_TYPE" VARCHAR(50) NULL,
 "COLUMN_INDEX" INT NULL,
 "COLUMN_COMMENT" VARCHAR(500) NULL,
  CLUSTER PRIMARY KEY("COLUMN_ID")  
);
CREATE TABLE "DIG_GEO"."DATASET_ROWS"
(
 "ROW_ID" VARCHAR(50) NOT NULL,
 "DATASET_ID" VARCHAR(50) NOT NULL,
 "ROW_INDEX" INT NULL,
 "ROW_DATA" CLOB NULL
);
CREATE TABLE "DIG_GEO"."DB_CONNECTIONS"
(
 "CONN_ID" VARCHAR(50) NOT NULL,
 "CONN_NAME" VARCHAR(200) NOT NULL,
 "DB_TYPE" VARCHAR(50) NOT NULL,
 "HOST" VARCHAR(200) NOT NULL,
 "PORT" INT NOT NULL,
 "USERNAME" VARCHAR(200) NOT NULL,
 "PASSWORD" VARCHAR(500) NOT NULL,
 "SCHEMA_NAME" VARCHAR(200) NULL,
 "CREATE_TIME" VARCHAR(50) NULL,
 "UPDATE_TIME" VARCHAR(50) NULL
);
CREATE TABLE "DIG_GEO"."ICONS"
(
 "ICON_ID" VARCHAR(50) NOT NULL,
 "CATEGORY_ID" VARCHAR(50) NOT NULL,
 "LIBRARY_CODE" VARCHAR(100) NULL,
 "CODE_NAME" VARCHAR(100) NULL,
 "FILE_NAME" VARCHAR(500) NULL,
 "ORIGINAL_NAME" VARCHAR(500) NULL,
 "FILE_TYPE" VARCHAR(20) NULL,
 "FILE_SIZE" BIGINT NULL,
 "URL" VARCHAR(500) NULL,
 "SORT_ORDER" INT NULL,
 "CREATE_TIME" VARCHAR(50) NULL
);
CREATE TABLE "DIG_GEO"."ICON_CATEGORIES"
(
 "CATEGORY_ID" VARCHAR(50) NOT NULL,
 "CATEGORY_NAME" VARCHAR(100) NULL,
 "SORT_ORDER" INT NULL,
 "CREATE_TIME" VARCHAR(50) NULL
);
CREATE TABLE "DIG_GEO"."LAYERS"
(
 "LAYER_ID" VARCHAR(50) NOT NULL,
 "PROJECT_ID" VARCHAR(50) NOT NULL,
 "DATASET_ID" VARCHAR(50) NULL,
 "LAYER_NAME" VARCHAR(200) NULL,
 "TYPE" VARCHAR(50) NULL,
 "VIS_CONFIG" CLOB NULL,
 "LAYER_ORDER" INT NULL,
 "CREATE_TIME" VARCHAR(50) NULL
);
CREATE TABLE "DIG_GEO"."PROJECTS"
(
 "PROJECT_ID" VARCHAR(50) NOT NULL,
 "PROJECT_NAME" VARCHAR(200) NULL,
 "DESCRIPTION" VARCHAR(500) NULL,
 "CREATE_TIME" VARCHAR(50) NULL,
 "UPDATE_TIME" VARCHAR(50) NULL,
 "THUMBNAIL" VARCHAR(500) NULL,
 "ASSET_PACKAGE_IDS" VARCHAR(500) NULL,
 "MAP_CONFIG" VARCHAR(4000) NULL
);
CREATE TABLE "DIG_GEO"."TILE_CONFIG"
(
 "ID" VARCHAR(50) NOT NULL,
 "TILE_URL" VARCHAR(500) NULL,
 "TILE_NAME" VARCHAR(100) NULL,
 "MIN_ZOOM" INT NULL,
 "MAX_ZOOM" INT NULL,
 "UPDATE_TIME" VARCHAR(50) NULL,
 "IS_DEFAULT" VARCHAR(50) NULL,
 "DEFAULT_NUM" INT NULL,
 "CRS" VARCHAR(50) NULL,
 "TILE_SCHEME" VARCHAR(50) NULL,
 "ORIGIN" VARCHAR(100) NULL,
  CLUSTER PRIMARY KEY("ID")  
);
CREATE TABLE "DIG_GEO"."WIDGETS"
(
 "WIDGET_ID" VARCHAR(50) NOT NULL,
 "PROJECT_ID" VARCHAR(50) NOT NULL,
 "CONTAINER_ID" VARCHAR(50) NULL,
 "WIDGET_NAME" VARCHAR(200) NULL,
 "TYPE" VARCHAR(50) NULL,
 "PROPERTIES" CLOB NULL,
 "SLOT" VARCHAR(50) NULL,
 "WIDGET_ORDER" INT NULL
);
INSERT INTO "DIG_GEO"."DATASETS"("DATASET_ID","PROJECT_ID","DATASET_NAME","TYPE","METADATA","CREATE_TIME","FILTER") VALUES('29010812-b64c-47bc-8613-7ae4cc958302','828696eb-9e1c-467f-b98c-97c44aa14fc3',null,'remote','{"name":"测试","refreshInterval":0,"_serviceType":"GET_DATABASE_DATA_LIST","_properties":{"connectionId":"8eb7a1d5-1fa0-4b4e-9b52-0bbb98b7ec69","tableName":"TILE_CONFIG"}}','2026-08-22 00:25:25',null);

INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('1ed646a8-e48d-485e-8586-5bdf1ea1b90d','29010812-b64c-47bc-8613-7ae4cc958302','TILE_URL','string',1,'XYZ瓦片地址模板 (含 {x} {y} {z} 占位符)');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('1efb4dbe-c852-44f9-a04f-f5d3ea836002','29010812-b64c-47bc-8613-7ae4cc958302','UPDATE_TIME','string',5,'最后修改时间');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('4c9a41f6-45af-4f08-93e4-95b5e82a641f','29010812-b64c-47bc-8613-7ae4cc958302','CRS','string',8,'坐标系类型');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('5abd2374-2c8a-41db-a9b2-99c258988abb','29010812-b64c-47bc-8613-7ae4cc958302','DEFAULT_NUM','number',7,'默认的层数');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('96290d83-4d3c-4dde-a54e-aa32b66ee380','29010812-b64c-47bc-8613-7ae4cc958302','MIN_ZOOM','number',3,'最小缩放级别, 默认0');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('9fafb65a-0105-4f3b-807a-8284263de0dd','29010812-b64c-47bc-8613-7ae4cc958302','MAX_ZOOM','number',4,'最大缩放级别, 默认18');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('bf74396b-1738-4d32-8dc9-edc793021c97','29010812-b64c-47bc-8613-7ae4cc958302','ORIGIN','string',10,null);
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('c0d107d8-a10c-48fc-8f54-3a472d14859c','29010812-b64c-47bc-8613-7ae4cc958302','TILE_NAME','string',2,'底图显示名称 (如 "内网卫星影像")');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('c2ba1ed6-2504-4ef3-88e1-89a774d05c93','29010812-b64c-47bc-8613-7ae4cc958302','TILE_SCHEME','string',9,'瓦片编号方式');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('e46a7e1d-e370-46a5-b047-45e5e091bdb4','29010812-b64c-47bc-8613-7ae4cc958302','IS_DEFAULT','string',6,'是否默认');
INSERT INTO "DIG_GEO"."DATASET_COLUMNS"("COLUMN_ID","DATASET_ID","COLUMN_NAME","COLUMN_TYPE","COLUMN_INDEX","COLUMN_COMMENT") VALUES('f7b35b68-504c-4287-b5f6-8be2b68ae8e0','29010812-b64c-47bc-8613-7ae4cc958302','ID','string',0,'主键, 固定值 "default", 单例');

INSERT INTO "DIG_GEO"."DB_CONNECTIONS"("CONN_ID","CONN_NAME","DB_TYPE","HOST","PORT","USERNAME","PASSWORD","SCHEMA_NAME","CREATE_TIME","UPDATE_TIME") VALUES('8eb7a1d5-1fa0-4b4e-9b52-0bbb98b7ec69','达梦测试','Dameng','localhost',5236,'SYSDBA','Labuse123123','DIG_GEO','2026-08-20 20:36:49','2026-08-21 23:45:54');

INSERT INTO "DIG_GEO"."PROJECTS"("PROJECT_ID","PROJECT_NAME","DESCRIPTION","CREATE_TIME","UPDATE_TIME","THUMBNAIL","ASSET_PACKAGE_IDS","MAP_CONFIG") VALUES('828696eb-9e1c-467f-b98c-97c44aa14fc3','未命名_2026-08-21 23:59:38','无描述信息','2026-08-21 23:59:38','2026-08-22 00:25:25',null,'["@antv/li-core-assets","@antv/li-analysis-assets"]','{"basemap":"Map","config":{"zoom":3,"center":[120.153576,30.287459],"pitch":0,"bearing":0,"style":"dark","WebGLParams":{"preserveDrawingBuffer":true}},"logoPosition":"leftbottom","logoVisible":false}');

INSERT INTO "DIG_GEO"."TILE_CONFIG"("ID","TILE_URL","TILE_NAME","MIN_ZOOM","MAX_ZOOM","UPDATE_TIME","IS_DEFAULT","DEFAULT_NUM","CRS","TILE_SCHEME","ORIGIN") VALUES('default','https://webrd0{1-4}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}','高德标准地图',0,18,'2026-08-01 11:59:28',null,null,null,null,null);

INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('AnalysisLayout','828696eb-9e1c-467f-b98c-97c44aa14fc3',null,null,'AnalysisLayout','{"metadata":{"name":"布局组件"},"properties":{"showFloatPanel":false,"showSidePanel":false,"showBottomPanel":false}}',null,0);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('ZoomControl','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'ZoomControl','{"metadata":{"name":"缩放器"},"properties":{"position":"bottomright"}}','controls',1);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('PropertiesPanel','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'PropertiesPanel','{"metadata":{"name":"属性面板"},"properties":{"isOpen":false,"items":[]}}','controls',2);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('LayerPopup','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'LayerPopup','{"metadata":{"name":"信息框"},"properties":{"isOpen":true,"trigger":"hover","items":[]}}','controls',3);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('FullscreenControl','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'FullscreenControl','{"metadata":{"name":"全屏切换"},"properties":{"position":"topright"}}','controls',4);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('LegendWidget','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'LegendWidget','{"metadata":{"name":"图例"},"properties":{"position":"topright"}}','controls',5);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('MouseLocationControl','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'MouseLocationControl','{"metadata":{"name":"光标经纬度"},"properties":{"position":"leftbottom"}}','controls',6);
INSERT INTO "DIG_GEO"."WIDGETS"("WIDGET_ID","PROJECT_ID","CONTAINER_ID","WIDGET_NAME","TYPE","PROPERTIES","SLOT","WIDGET_ORDER") VALUES('ea0b8946-3e3d-4a87-a4a0-5dd08e7a2eed','828696eb-9e1c-467f-b98c-97c44aa14fc3','AnalysisLayout',null,'ExportImageControl','{"metadata":{"name":"地图截图"},"properties":{"position":"topright"}}','controls',7);

ALTER TABLE "DIG_GEO"."DATASETS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("DATASET_ID") ;
ALTER TABLE "DIG_GEO"."DATASET_ROWS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ROW_ID") ;
ALTER TABLE "DIG_GEO"."DB_CONNECTIONS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("CONN_ID") ;
ALTER TABLE "DIG_GEO"."ICONS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ICON_ID") ;
ALTER TABLE "DIG_GEO"."ICON_CATEGORIES" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("CATEGORY_ID") ;
ALTER TABLE "DIG_GEO"."LAYERS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("LAYER_ID") ;
ALTER TABLE "DIG_GEO"."PROJECTS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("PROJECT_ID") ;
ALTER TABLE "DIG_GEO"."WIDGETS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("WIDGET_ID") ;
CREATE INDEX "IDX_DATASETS_PROJECT"
ON "DIG_GEO"."DATASETS"("PROJECT_ID");
ALTER INDEX "DIG_GEO"."IDX_DATASETS_PROJECT" VISIBLE;
CREATE INDEX "IDX_COLUMNS_DATASET"
ON "DIG_GEO"."DATASET_COLUMNS"("DATASET_ID");
ALTER INDEX "DIG_GEO"."IDX_COLUMNS_DATASET" VISIBLE;
CREATE INDEX "IDX_ROWS_DATASET"
ON "DIG_GEO"."DATASET_ROWS"("DATASET_ID","ROW_INDEX");
ALTER INDEX "DIG_GEO"."IDX_ROWS_DATASET" VISIBLE;
CREATE INDEX "IDX_DB_CONN_NAME"
ON "DIG_GEO"."DB_CONNECTIONS"("CONN_NAME");
ALTER INDEX "DIG_GEO"."IDX_DB_CONN_NAME" VISIBLE;
CREATE INDEX "IDX_LAYERS_PROJECT"
ON "DIG_GEO"."LAYERS"("PROJECT_ID","LAYER_ORDER");
ALTER INDEX "DIG_GEO"."IDX_LAYERS_PROJECT" VISIBLE;
CREATE INDEX "IDX_PROJECTS_CREATE_TIME"
ON "DIG_GEO"."PROJECTS"("CREATE_TIME");
ALTER INDEX "DIG_GEO"."IDX_PROJECTS_CREATE_TIME" VISIBLE;
CREATE INDEX "IDX_PROJECTS_NAME"
ON "DIG_GEO"."PROJECTS"("PROJECT_NAME");
ALTER INDEX "DIG_GEO"."IDX_PROJECTS_NAME" VISIBLE;
CREATE INDEX "IDX_WIDGETS_PROJECT"
ON "DIG_GEO"."WIDGETS"("PROJECT_ID","WIDGET_ORDER");
ALTER INDEX "DIG_GEO"."IDX_WIDGETS_PROJECT" VISIBLE;
ALTER TABLE "DIG_GEO"."ICONS" ADD CONSTRAINT "UNQ_ICON_CODE" UNIQUE("CATEGORY_ID","LIBRARY_CODE","CODE_NAME") ;
COMMENT ON TABLE "DIG_GEO"."DB_CONNECTIONS" IS '外部数据库连接配置表';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."CONN_ID" IS '连接ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."CONN_NAME" IS '连接名称 (用户自定义)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."CREATE_TIME" IS '创建时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."DB_TYPE" IS '数据库类型: MySQL / Dameng';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."HOST" IS '主机IP地址';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."PASSWORD" IS '数据库密码 (内网明文存储)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."PORT" IS '端口号';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."SCHEMA_NAME" IS '模式名 (Schema/Database)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."UPDATE_TIME" IS '最后修改时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN "DIG_GEO"."DB_CONNECTIONS"."USERNAME" IS '数据库用户名';
COMMENT ON TABLE "DIG_GEO"."ICON_CATEGORIES" IS '图标分类表';
COMMENT ON COLUMN "DIG_GEO"."ICON_CATEGORIES"."CATEGORY_ID" IS '分类ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."ICON_CATEGORIES"."CATEGORY_NAME" IS '分类名称 (如 "通信", "军事", "交通")';
COMMENT ON COLUMN "DIG_GEO"."ICON_CATEGORIES"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DIG_GEO"."ICON_CATEGORIES"."SORT_ORDER" IS '排序序号';
COMMENT ON TABLE "DIG_GEO"."PROJECTS" IS '项目主表';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."ASSET_PACKAGE_IDS" IS '资产包ID列表 (JSON数组)';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."CREATE_TIME" IS '创建时间 (yyyy-MM-dd HH:mm:ss)';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."DESCRIPTION" IS '项目描述';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."PROJECT_ID" IS '项目ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."PROJECT_NAME" IS '项目名称';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."THUMBNAIL" IS '缩略图 URL';
COMMENT ON COLUMN "DIG_GEO"."PROJECTS"."UPDATE_TIME" IS '最后修改时间';
COMMENT ON TABLE "DIG_GEO"."TILE_CONFIG" IS '瓦片全局配置表 (仅1条记录)';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."CRS" IS '坐标系类型';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."DEFAULT_NUM" IS '默认的层数';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."ID" IS '主键, 固定值 "default", 单例';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."IS_DEFAULT" IS '是否默认';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."MAX_ZOOM" IS '最大缩放级别, 默认18';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."MIN_ZOOM" IS '最小缩放级别, 默认0';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."TILE_NAME" IS '底图显示名称 (如 "内网卫星影像")';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."TILE_SCHEME" IS '瓦片编号方式';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."TILE_URL" IS 'XYZ瓦片地址模板 (含 {x} {y} {z} 占位符)';
COMMENT ON COLUMN "DIG_GEO"."TILE_CONFIG"."UPDATE_TIME" IS '最后修改时间';
ALTER TABLE "DIG_GEO"."DATASETS" ADD CONSTRAINT "FK_DATASETS_PROJECT" FOREIGN KEY("PROJECT_ID") REFERENCES "DIG_GEO"."PROJECTS"("PROJECT_ID") ON DELETE CASCADE  ;
ALTER TABLE "DIG_GEO"."DATASET_COLUMNS" ADD CONSTRAINT "FK_COLUMNS_DATASET" FOREIGN KEY("DATASET_ID") REFERENCES "DIG_GEO"."DATASETS"("DATASET_ID") ON DELETE CASCADE  ;
ALTER TABLE "DIG_GEO"."DATASET_ROWS" ADD CONSTRAINT "FK_ROWS_DATASET" FOREIGN KEY("DATASET_ID") REFERENCES "DIG_GEO"."DATASETS"("DATASET_ID") ON DELETE CASCADE  ;
ALTER TABLE "DIG_GEO"."LAYERS" ADD CONSTRAINT "FK_LAYERS_PROJECT" FOREIGN KEY("PROJECT_ID") REFERENCES "DIG_GEO"."PROJECTS"("PROJECT_ID") ON DELETE CASCADE  ;
ALTER TABLE "DIG_GEO"."LAYERS" ADD CONSTRAINT "FK_LAYERS_DATASET" FOREIGN KEY("DATASET_ID") REFERENCES "DIG_GEO"."DATASETS"("DATASET_ID") ON DELETE SET NULL  ;
ALTER TABLE "DIG_GEO"."WIDGETS" ADD CONSTRAINT "FK_WIDGETS_PROJECT" FOREIGN KEY("PROJECT_ID") REFERENCES "DIG_GEO"."PROJECTS"("PROJECT_ID") ON DELETE CASCADE  ;
ALTER TABLE "DIG_GEO"."WIDGETS" ADD CONSTRAINT "FK_WIDGETS_CONTAINER" FOREIGN KEY("CONTAINER_ID") REFERENCES "DIG_GEO"."WIDGETS"("WIDGET_ID") ON DELETE SET NULL  with index ;
CREATE INDEX "IDX_ICONS_CATEGORY"
ON "DIG_GEO"."ICONS"("CATEGORY_ID","SORT_ORDER");
ALTER INDEX "DIG_GEO"."IDX_ICONS_CATEGORY" VISIBLE;
CREATE INDEX "IDX_ICONS_LOOKUP"
ON "DIG_GEO"."ICONS"("LIBRARY_CODE","CODE_NAME");
ALTER INDEX "DIG_GEO"."IDX_ICONS_LOOKUP" VISIBLE;
COMMENT ON TABLE "DIG_GEO"."DATASETS" IS '数据集元数据表';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."DATASET_ID" IS '数据集ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."DATASET_NAME" IS '数据集名称';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."FILTER" IS 'JSON, 筛选器元信息';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."METADATA" IS 'JSON, 数据集元信息 (columnsMeta, rowCount 等)';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."PROJECT_ID" IS '所属项目ID';
COMMENT ON COLUMN "DIG_GEO"."DATASETS"."TYPE" IS '数据源类型: local / remote / raster-tile / vector-tile / doris';
COMMENT ON TABLE "DIG_GEO"."DATASET_COLUMNS" IS '数据集列定义表';
COMMENT ON COLUMN "DIG_GEO"."DATASET_COLUMNS"."COLUMN_ID" IS '列ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."DATASET_COLUMNS"."COLUMN_INDEX" IS '列序号 (0开始), 对应 row_data JSON数组下标';
COMMENT ON COLUMN "DIG_GEO"."DATASET_COLUMNS"."COLUMN_NAME" IS '列名 (如"城市", "人口")';
COMMENT ON COLUMN "DIG_GEO"."DATASET_COLUMNS"."COLUMN_TYPE" IS '数据类型: string / number / boolean / date';
COMMENT ON COLUMN "DIG_GEO"."DATASET_COLUMNS"."DATASET_ID" IS '所属数据集ID';
COMMENT ON TABLE "DIG_GEO"."DATASET_ROWS" IS '数据行表';
COMMENT ON COLUMN "DIG_GEO"."DATASET_ROWS"."DATASET_ID" IS '所属数据集ID';
COMMENT ON COLUMN "DIG_GEO"."DATASET_ROWS"."ROW_DATA" IS 'JSON数组, 按 column_index 顺序存储值';
COMMENT ON COLUMN "DIG_GEO"."DATASET_ROWS"."ROW_ID" IS '行ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."DATASET_ROWS"."ROW_INDEX" IS '行序号 (0开始)';
COMMENT ON TABLE "DIG_GEO"."LAYERS" IS '图层配置表';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."DATASET_ID" IS '关联数据集ID (可选)';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."LAYER_ID" IS '图层ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."LAYER_NAME" IS '图层名称';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."LAYER_ORDER" IS '图层叠放顺序';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."PROJECT_ID" IS '所属项目ID';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."TYPE" IS '图层类型: BubbleLayer / TileLayer / IconLayer / FlowLayer 等';
COMMENT ON COLUMN "DIG_GEO"."LAYERS"."VIS_CONFIG" IS 'JSON, 可视化配置 (颜色、半径、透明度、图标等)';
COMMENT ON TABLE "DIG_GEO"."WIDGETS" IS '组件配置表';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."CONTAINER_ID" IS '父容器组件ID (可选, 自引用)';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."PROJECT_ID" IS '所属项目ID';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."PROPERTIES" IS 'JSON, 组件属性配置';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."SLOT" IS '插槽名 (如 controls)';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."TYPE" IS '组件类型: AnalysisLayout / ZoomControl / Legend 等';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."WIDGET_ID" IS '组件ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."WIDGET_NAME" IS '组件名称';
COMMENT ON COLUMN "DIG_GEO"."WIDGETS"."WIDGET_ORDER" IS '排序序号';
ALTER TABLE "DIG_GEO"."ICONS" ADD CONSTRAINT "FK_ICONS_CATEGORY" FOREIGN KEY("CATEGORY_ID") REFERENCES "DIG_GEO"."ICON_CATEGORIES"("CATEGORY_ID") ON DELETE CASCADE  ;
COMMENT ON TABLE "DIG_GEO"."ICONS" IS '图标元数据表';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."CATEGORY_ID" IS '所属分类ID';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."CODE_NAME" IS '代号 (用户自定义)';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."FILE_NAME" IS '服务器存储文件名 (UUID重命名)';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."FILE_SIZE" IS '文件大小 (字节)';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."FILE_TYPE" IS '文件类型: svg / png / jpg 等';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."ICON_ID" IS '图标ID (UUID)';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."LIBRARY_CODE" IS '库号 (用户自定义)';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."ORIGINAL_NAME" IS '原始文件名';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."SORT_ORDER" IS '分类内排序序号';
COMMENT ON COLUMN "DIG_GEO"."ICONS"."URL" IS '图标访问 URL (如 /icons/{categoryId}/{uuid}.{ext})';
